# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7c8a462621f58682b434c3b3da61c035"
name = "pos-app"
handle = "pos-app-59"
application_url = "https://terminals-relatively-downloaded-randy.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://terminals-relatively-downloaded-randy.trycloudflare.com/auth/callback",
  "https://terminals-relatively-downloaded-randy.trycloudflare.com/auth/shopify/callback",
  "https://terminals-relatively-downloaded-randy.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
